In [1]:
# Aim: Focus on pinpointing the most popular locations through Hadoop Map Reduce
# Most popular location could be on the basis of number of reviews, ratings, and review per month

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Itisha Sharma\Desktop\MDX\CST4070 – Applied Data Analytics\W16\listings.csv")
df.shape

C:\Users\Itisha Sharma\AppData\Local\Temp\ipykernel_30100\422649575.py:2: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\Itisha Sharma\Desktop\MDX\CST4070 – Applied Data Analytics\W16\listings.csv")

(87946, 75)

In [3]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,92644,https://www.airbnb.com/rooms/92644,20230906022807,2023-09-06,city scrape,Rental unit in Earlsfield · ★4.57 · 1 bedroom ...,<b>The space</b><br />Hi everyone! I have 2 ro...,NaN,https://a0.muscache.com/pictures/715127/85bdb4...,498201,...,4.67,4.53,4.68,NaN,t,1,0,1,0,1.45
1,93015,https://www.airbnb.com/rooms/93015,20230906022807,2023-09-06,city scrape,Rental unit in Hammersmith · ★4.82 · 2 bedroom...,Gorgeous 2 bed ground floor apartment with per...,A bit of history about the W14 area: <br />Com...,https://a0.muscache.com/pictures/865937ec-ee56...,499704,...,4.88,4.85,4.74,NaN,f,1,1,0,0,0.27
2,13913,https://www.airbnb.com/rooms/13913,20230906022807,2023-09-06,city scrape,Rental unit in Islington · ★4.80 · 1 bedroom ·...,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.82,4.69,4.69,NaN,f,2,1,1,0,0.26
3,15400,https://www.airbnb.com/rooms/15400,20230906022807,2023-09-06,city scrape,Rental unit in London · ★4.80 · 1 bedroom · 1 ...,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.83,4.93,4.74,NaN,f,1,1,0,0,0.56
4,93734,https://www.airbnb.com/rooms/93734,20230906022807,2023-09-07,city scrape,Condo in London · ★4.62 · 1 bedroom · 1 bed · ...,<b>During your stay</b><br />I’m a professiona...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,497514,...,4.81,4.64,4.67,NaN,f,1,0,1,0,1.21

In [4]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [6]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df.dtypes

id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
source                                           object
name                                             object
description                                      object
neighborhood_overview                            object
picture_url                                      object
host_id                                           int64
host_url                                         object
host_name                                        object
host_since                                       object
host_location                                    object
host_about                                       object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                             object
host_is_superhost                                object
host_thumbnail_url                               object
host_picture_url                                 object
host_neighbourhood                               object
host_listings_count                             float64
host_total_listings_count                       float64
host_verifications                               object
host_has_profile_pic                             object
host_identity_verified                           object
neighbourhood                                    object
neighbourhood_cleansed                           object
neighbourhood_group_cleansed                    float64
latitude                                        float64
longitude                                       float64
property_type                                    object
room_type                                        object
accommodates                                      int64
bathrooms                                       float64
bathrooms_text                                   object
bedrooms                                        float64
beds                                            float64
amenities                                        object
price                                            object
minimum_nights                                    int64
maximum_nights                                    int64
minimum_minimum_nights                          float64
maximum_minimum_nights                          float64
minimum_maximum_nights                          float64
maximum_maximum_nights                          float64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                float64
has_availability                                 object
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                            object
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
number_of_reviews_l30d                            int64
first_review                                     object
last_review                                      object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
license                                          object
instant_bookable                                 object
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
dtype: object

In [7]:
import pandas as pd

# Set display options to show all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Display the null values column-wise
print(df.isnull().sum())

id                                                  0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
source                                              0
name                                                0
description                                      1267
neighborhood_overview                           40756
picture_url                                         3
host_id                                             0
host_url                                            0
host_name                                           5
host_since                                          5
host_location                                   18778
host_about                                      42040
host_response_time                              28918
host_response_rate                              28918
host_acceptance_rate                            25188
host_is_superhost                                 932
host_thumbnail_url                                  5
host_picture_url                                    5
host_neighbourhood                              39867
host_listings_count                                 5
host_total_listings_count                           5
host_verifications                                  5
host_has_profile_pic                                5
host_identity_verified                              5
neighbourhood                                   40755
neighbourhood_cleansed                              0
neighbourhood_group_cleansed                    87946
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                       87946
bathrooms_text                                    103
bedrooms                                        32774
beds                                             1134
amenities                                           0
price                                               0
minimum_nights                                      0
maximum_nights                                      0
minimum_minimum_nights                              1
maximum_minimum_nights                              1
minimum_maximum_nights                              1
maximum_maximum_nights                              1
minimum_nights_avg_ntm                              1
maximum_nights_avg_ntm                              1
calendar_updated                                87946
has_availability                                    0
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
first_review                                    22158
last_review                                     22158
review_scores_rating                            22158
review_scores_accuracy                          23093
review_scores_cleanliness                       23081
review_scores_checkin                           23125
review_scores_communication                     23095
review_scores_location                          23125
review_scores_value                             23126
license                                         87945
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                               22158
dtype: int64

This program will print the DataFrame df with a new column named 'dates_2022', containing dates from both columns ('first_review' and 'last_review') that occurred in the year 2022. If the year is 2022, it concatenates both dates into a single string in the format "DD-MM-YYYY, DD-MM-YYYY" and puts it in the new column 'dates_2022'.

In [13]:
# Convert string dates to datetime format
df['first_review'] = pd.to_datetime(df['first_review'], format='%Y-%m-%d')
df['last_review'] = pd.to_datetime(df['last_review'], format='%Y-%m-%d')

In [17]:
# Convert string dates to datetime format


# Create a new column 'dates_2022' containing dates from 'first_review' and 'last_review' that are in the year 2022
df['dates_2022'] = df.apply(lambda row: row['first_review'].strftime('%d-%m-%Y') + ', ' + row['last_review'].strftime('%d-%m-%Y') if row['first_review'].year == 2022 or row['last_review'].year == 2022 else 'Null', axis=1)

# Print the DataFrame with the new column
print("DataFrame with 'dates_2022' column:")
df.head()

DataFrame with 'dates_2022' column:

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,dates_2022
0,92644,https://www.airbnb.com/rooms/92644,20230906022807,2023-09-06,city scrape,Rental unit in Earlsfield · ★4.57 · 1 bedroom ...,<b>The space</b><br />Hi everyone! I have 2 ro...,NaN,https://a0.muscache.com/pictures/715127/85bdb4...,498201,https://www.airbnb.com/users/show/498201,Dee Dee,2011-04-10,"London, United Kingdom",I am employed at St Georges hospital in tootin...,NaN,NaN,100%,f,https://a0.muscache.com/im/pictures/user/0edcb...,https://a0.muscache.com/im/pictures/user/0edcb...,Earlsfield,1.0,1.0,"['email', 'phone']",t,t,NaN,Wandsworth,NaN,51.44201,-0.18739,Private room in rental unit,Private room,2,NaN,1.5 shared baths,NaN,2.0,"[""Heating"", ""TV with standard cable"", ""Wifi"", ...",$42.00,2,730,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,0,0,0,217,2023-09-06,216,9,0,2011-06-21,2022-10-29,4.57,4.74,4.86,4.71,4.67,4.53,4.68,NaN,t,1,0,1,0,1.45,"21-06-2011, 29-10-2022"
1,93015,https://www.airbnb.com/rooms/93015,20230906022807,2023-09-06,city scrape,Rental unit in Hammersmith · ★4.82 · 2 bedroom...,Gorgeous 2 bed ground floor apartment with per...,A bit of history about the W14 area: <br />Com...,https://a0.muscache.com/pictures/865937ec-ee56...,499704,https://www.airbnb.com/users/show/499704,Sarah,2011-04-11,"London, United Kingdom",Been living in London for over 20 years and I ...,within a few hours,100%,25%,f,https://a0.muscache.com/im/pictures/user/452ff...,https://a0.muscache.com/im/pictures/user/452ff...,Hammersmith,1.0,2.0,"['email', 'phone']",t,t,"Hammersmith, England, United Kingdom",Hammersmith and Fulham,NaN,51.49993,-0.21707,Entire rental unit,Entire home/apt,5,NaN,1 bath,2.0,3.0,"[""Window guards"", ""Bathtub"", ""Hot water kettle...",$175.00,5,240,5.0,5.0,240.0,240.0,5.0,240.0,NaN,t,13,18,38,40,2023-09-06,38,2,0,2012-02-01,2022-09-30,4.82,4.76,4.62,4.85,4.88,4.85,4.74,NaN,f,1,1,0,0,0.27,"01-02-2012, 30-09-2022"
2,13913,https://www.airbnb.com/rooms/13913,20230906022807,2023-09-06,city scrape,Rental unit in Islington · ★4.80 · 1 bedroom ·...,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,https://www.airbnb.com/users/show/54730,Alina,2009-11-16,"London, United Kingdom",I am a Multi-Media Visual Artist and Creative ...,within a few hours,100%,88%,f,https://a0.muscache.com/im/users/54730/profile...,https://a0.muscache.com/im/users/54730/profile...,LB of Islington,3.0,4.0,"['email', 'phone']",t,t,"Islington, Greater London, United Kingdom",Islington,NaN,51.56861,-0.11270,Private room in rental unit,Private room,1,NaN,1 shared bath,NaN,1.0,"[""Bathtub"", ""Hot water kettle"", ""Laundromat ne...",$79.00,1,29,1.0,1.0,29.0,29.0,1.0,29.0,NaN,t,25,55,85,360,2023-09-06,41,11,0,2010-08-18,2022-12-11,4.80,4.72,4.72,4.74,4.82,4.69,4.69,NaN,f,2,1,1,0,0.26,"18-08-2010, 11-12-2022"
3,15400,https://www.airbnb.com/rooms/15400,20230906022807,2023-09-06,city scrape,Rental unit in London · ★4.80 · 1 bedroom · 1 ...,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,https://www.airbnb.com/users/show/60302,Philippa,2009-12-05,"Royal Borough of Kensington and Chelsea, Unite...","English, grandmother, I have travelled quite ...",within a day,100%,41%,f,https://a0.muscache.com/im/users/60302/profile...,https://a0.muscache.com/im/users/60302/profile...,Chelsea,1.0,12.0,"['email', 'phone']",t,t,"London, United Kingdom",Kensington and Chelsea,NaN,51.48780,-0.16813,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,1.0,"[""Shampoo"", ""Luggage dropoff allowed"", ""Dryer""...",$150.00,7,30,7.0,7.0,30.0,30.0,7.0,30.0,NaN,t,7,7,7,73,2023-09-06,94,5,0,2009-12-21,2023-05-01,4.80,4.85,4.88,4.88,4.83,4.93,4.74,NaN,f,1,1,0,0,0.56,Null
4,93734,https://www.airbnb.com/rooms/93734,20230906022807,2023-09-07,city scrape,Condo in London · ★4.62 · 1 bedroom · 1 bed · ...,<b>During your stay</b><br />I’m a professiona...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,497514,https://www.airbnb.com/users/show/497514,William,2011-04-10,"London, United Kingdom",I’m a maverick by nature. Restless and curious...,within a few hours,90%,75%,t,https://a0.muscache.com/im/users/497514/profil...,https://a0.muscache.com/im/users/497514/profil...,Greenwich,1.0,1.0,"['email', 'phone']",t,t,NaN,Greenwich,NaN,51.47618,0.01442,Private room in condo,Private room,2,NaN,1 shared bath,NaN,1.0,"[""Window guards"", ""Bathtub"", ""Hot water kettle...",$46.00,4,365,2.0,4.0,365.0,365.0,4.0,365.0,NaN,t,5,5,5,196,2023-09-07,180,25,3,2011-06-30,2023-09-02,4.62,4.70,4.59,4.63,4.81,4.64,4.67,NaN,f,1,0,1,0,1.21,Null

In [18]:
df.isnull().sum()

id                                                  0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
source                                              0
name                                                0
description                                      1267
neighborhood_overview                           40756
picture_url                                         3
host_id                                             0
host_url                                            0
host_name                                           5
host_since                                          5
host_location                                   18778
host_about                                      42040
host_response_time                              28918
host_response_rate                              28918
host_acceptance_rate                            25188
host_is_superhost                                 932
host_thumbnail_url                                  5
host_picture_url                                    5
host_neighbourhood                              39867
host_listings_count                                 5
host_total_listings_count                           5
host_verifications                                  5
host_has_profile_pic                                5
host_identity_verified                              5
neighbourhood                                   40755
neighbourhood_cleansed                              0
neighbourhood_group_cleansed                    87946
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                       87946
bathrooms_text                                    103
bedrooms                                        32774
beds                                             1134
amenities                                           0
price                                               0
minimum_nights                                      0
maximum_nights                                      0
minimum_minimum_nights                              1
maximum_minimum_nights                              1
minimum_maximum_nights                              1
maximum_maximum_nights                              1
minimum_nights_avg_ntm                              1
maximum_nights_avg_ntm                              1
calendar_updated                                87946
has_availability                                    0
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
first_review                                    22158
last_review                                     22158
review_scores_rating                            22158
review_scores_accuracy                          23093
review_scores_cleanliness                       23081
review_scores_checkin                           23125
review_scores_communication                     23095
review_scores_location                          23125
review_scores_value                             23126
license                                         87945
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                               22158
dates_2022                                          0
dtype: int64

In [24]:
# Assuming df_reviews is your DataFrame
# Selecting the desired columns
df_reviews_rating = df[['neighbourhood_cleansed', 'review_scores_rating','dates_2022']]
df_reviews_rating.head()
# Displaying the first few rows of the new dataset
#df_reviews_rating=df_reviews_rating.dropna()
#df_reviews_rating.to_csv('Review_ratings_location.csv')
df_reviews_rating.shape

(87946, 3)

In [25]:
df_reviews_rating.isnull().sum()

neighbourhood_cleansed        0
review_scores_rating      22158
dates_2022                    0
dtype: int64

In [21]:
# Count the number of rows with 'Null' value in 'dates_2022' column
num_null_rows = (df['dates_2022'] == 'Null').sum()

# Print the number of rows with 'Null' value
print("Number of rows with 'Null' value in 'dates_2022':", num_null_rows)

Number of rows with 'Null' value in 'dates_2022': 72157

In [27]:
# Drop null values in review_scores_rating column
df_reviews_rating_dropna=df_reviews_rating.dropna()
df_reviews_rating_dropna.shape

(65788, 3)

In [28]:
# Drop rows with 'Null' value under 'dates_2022'
df_reviews_rating_dropnull = df_reviews_rating_dropna[df_reviews_rating_dropna['dates_2022'] != 'Null']
df_reviews_rating_dropnull.shape

(15789, 3)

In [29]:
df_reviews_rating_dropnull.head()

   neighbourhood_cleansed  review_scores_rating              dates_2022
0              Wandsworth                  4.57  21-06-2011, 29-10-2022
1  Hammersmith and Fulham                  4.82  01-02-2012, 30-09-2022
2               Islington                  4.80  18-08-2010, 11-12-2022
5             Westminster                  4.76  21-03-2011, 19-11-2022
7              Wandsworth                  4.90  15-11-2010, 19-07-2022

In [30]:
df_reviews_rating_dropnull.to_csv('Review_rating_2022_final.csv')

In [31]:
#Number of reviews
df_reviews_counts = df[['neighbourhood_cleansed', 'number_of_reviews','dates_2022']]
df_reviews_counts.shape

(87946, 3)

In [32]:
df_reviews_counts.isnull().sum()

neighbourhood_cleansed    0
number_of_reviews         0
dates_2022                0
dtype: int64

In [33]:
#Dropping the rows with 'Null' as the value in dates_2022 column
df_reviews_counts_dropnull = df_reviews_counts[df_reviews_counts['dates_2022'] != 'Null']
df_reviews_counts_dropnull.shape

(15789, 3)

In [34]:
df_reviews_counts_dropnull.to_csv('Review_counts_2022_final.csv')

In [25]:
df_num_reviews_cleaned.head()

   neighbourhood_cleansed  reviews_per_month
0              Wandsworth               1.45
1  Hammersmith and Fulham               0.27
2               Islington               0.26
3  Kensington and Chelsea               0.56
4               Greenwich               1.21

In [27]:
df_num_reviews_cleaned.to_csv('number_of_reviews.csv')